# Generated by Django 6.0.6 on 2026-07-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0002_userregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('category', models.CharField(choices=[('AC', 'AC Service'), ('PLUMBER', 'Plumber Service'), ('ELECTRICAL', 'Electrical Service'), ('INVERTER', 'Inverter Service')], max_length=20)),
                ('experience', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='workers/')),
            ],
        ),
    ]
