# Generated by Django 6.0.6 on 2026-08-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0005_remove_booking_booking_status_booking_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregistration',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
